/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrderDetailsIndexRouteImport } from './routes/orderDetails/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ErrorIndexRouteImport } from './routes/error/index'
import { Route as ShoppingCartIndexRouteImport } from './routes/ShoppingCart/index'
import { Route as OrderHistoryIndexRouteImport } from './routes/OrderHistory/index'
import { Route as OrderConfirmationPageIndexRouteImport } from './routes/OrderConfirmationPage/index'
import { Route as ProductSearchRouteImport } from './routes/product/search'
import { Route as ProductProductNotFoundRouteImport } from './routes/product/productNotFound'
import { Route as ProductListingPageRouteImport } from './routes/product/listingPage'
import { Route as ProductProductIdRouteImport } from './routes/product/$productId'
import { Route as CheckOutPageTidRouteImport } from './routes/CheckOutPage/$tid'
import { Route as ProductCategoryCategoryRouteImport } from './routes/product/category.$category'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderDetailsIndexRoute = OrderDetailsIndexRouteImport.update({
  id: '/orderDetails/',
  path: '/orderDetails/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorIndexRoute = ErrorIndexRouteImport.update({
  id: '/error/',
  path: '/error/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingCartIndexRoute = ShoppingCartIndexRouteImport.update({
  id: '/ShoppingCart/',
  path: '/ShoppingCart/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderHistoryIndexRoute = OrderHistoryIndexRouteImport.update({
  id: '/OrderHistory/',
  path: '/OrderHistory/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationPageIndexRoute =
  OrderConfirmationPageIndexRouteImport.update({
    id: '/OrderConfirmationPage/',
    path: '/OrderConfirmationPage/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductSearchRoute = ProductSearchRouteImport.update({
  id: '/product/search',
  path: '/product/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductNotFoundRoute = ProductProductNotFoundRouteImport.update({
  id: '/product/productNotFound',
  path: '/product/productNotFound',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductListingPageRoute = ProductListingPageRouteImport.update({
  id: '/product/listingPage',
  path: '/product/listingPage',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckOutPageTidRoute = CheckOutPageTidRouteImport.update({
  id: '/CheckOutPage/$tid',
  path: '/CheckOutPage/$tid',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductCategoryCategoryRoute = ProductCategoryCategoryRouteImport.update({
  id: '/product/category/$category',
  path: '/product/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/CheckOutPage/$tid': typeof CheckOutPageTidRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/product/listingPage': typeof ProductListingPageRoute
  '/product/productNotFound': typeof ProductProductNotFoundRoute
  '/product/search': typeof ProductSearchRoute
  '/OrderConfirmationPage': typeof OrderConfirmationPageIndexRoute
  '/OrderHistory': typeof OrderHistoryIndexRoute
  '/ShoppingCart': typeof ShoppingCartIndexRoute
  '/error': typeof ErrorIndexRoute
  '/login': typeof LoginIndexRoute
  '/orderDetails': typeof OrderDetailsIndexRoute
  '/product/category/$category': typeof ProductCategoryCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/CheckOutPage/$tid': typeof CheckOutPageTidRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/product/listingPage': typeof ProductListingPageRoute
  '/product/productNotFound': typeof ProductProductNotFoundRoute
  '/product/search': typeof ProductSearchRoute
  '/OrderConfirmationPage': typeof OrderConfirmationPageIndexRoute
  '/OrderHistory': typeof OrderHistoryIndexRoute
  '/ShoppingCart': typeof ShoppingCartIndexRoute
  '/error': typeof ErrorIndexRoute
  '/login': typeof LoginIndexRoute
  '/orderDetails': typeof OrderDetailsIndexRoute
  '/product/category/$category': typeof ProductCategoryCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/CheckOutPage/$tid': typeof CheckOutPageTidRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/product/listingPage': typeof ProductListingPageRoute
  '/product/productNotFound': typeof ProductProductNotFoundRoute
  '/product/search': typeof ProductSearchRoute
  '/OrderConfirmationPage/': typeof OrderConfirmationPageIndexRoute
  '/OrderHistory/': typeof OrderHistoryIndexRoute
  '/ShoppingCart/': typeof ShoppingCartIndexRoute
  '/error/': typeof ErrorIndexRoute
  '/login/': typeof LoginIndexRoute
  '/orderDetails/': typeof OrderDetailsIndexRoute
  '/product/category/$category': typeof ProductCategoryCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/CheckOutPage/$tid'
    | '/product/$productId'
    | '/product/listingPage'
    | '/product/productNotFound'
    | '/product/search'
    | '/OrderConfirmationPage'
    | '/OrderHistory'
    | '/ShoppingCart'
    | '/error'
    | '/login'
    | '/orderDetails'
    | '/product/category/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/CheckOutPage/$tid'
    | '/product/$productId'
    | '/product/listingPage'
    | '/product/productNotFound'
    | '/product/search'
    | '/OrderConfirmationPage'
    | '/OrderHistory'
    | '/ShoppingCart'
    | '/error'
    | '/login'
    | '/orderDetails'
    | '/product/category/$category'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/CheckOutPage/$tid'
    | '/product/$productId'
    | '/product/listingPage'
    | '/product/productNotFound'
    | '/product/search'
    | '/OrderConfirmationPage/'
    | '/OrderHistory/'
    | '/ShoppingCart/'
    | '/error/'
    | '/login/'
    | '/orderDetails/'
    | '/product/category/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CheckOutPageTidRoute: typeof CheckOutPageTidRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  ProductListingPageRoute: typeof ProductListingPageRoute
  ProductProductNotFoundRoute: typeof ProductProductNotFoundRoute
  ProductSearchRoute: typeof ProductSearchRoute
  OrderConfirmationPageIndexRoute: typeof OrderConfirmationPageIndexRoute
  OrderHistoryIndexRoute: typeof OrderHistoryIndexRoute
  ShoppingCartIndexRoute: typeof ShoppingCartIndexRoute
  ErrorIndexRoute: typeof ErrorIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  OrderDetailsIndexRoute: typeof OrderDetailsIndexRoute
  ProductCategoryCategoryRoute: typeof ProductCategoryCategoryRoute
}

declare module '@tanstack/react-router' {
//   interface FileRoutesByPath {
//     '/$': {
//       id: '/$'
//       path: '/$'
//       fullPath: '/$'
//       preLoaderRoute: typeof SplatRouteImport
//       parentRoute: typeof rootRouteImport
//     }
//     '/': {
//       id: '/'
//       path: '/'
//       fullPath: '/'
//       preLoaderRoute: typeof IndexRouteImport
//       parentRoute: typeof rootRouteImport
//     }
//     '/orderDetails/': {
//       id: '/orderDetails/'
//       path: '/orderDetails'
//       fullPath: '/orderDetails'
//       preLoaderRoute: typeof OrderDetailsIndexRouteImport
//       parentRoute: typeof rootRouteImport
//     }
//     '/login/': {
//       id: '/login/'
//       path: '/login'
//       fullPath: '/login'
//       preLoaderRoute: typeof LoginIndexRouteImport
//       parentRoute: typeof rootRouteImport
//     }
//     '/error/': {
//       id: '/error/'
//       path: '/error'
//       fullPath: '/error'
//       preLoaderRoute: typeof ErrorIndexRouteImport
//       parentRoute: typeof rootRouteImport
//     }
//     '/ShoppingCart/': {
//       id: '/ShoppingCart/'
//       path: '/ShoppingCart'
//       fullPath: '/ShoppingCart'
//       preLoaderRoute: typeof ShoppingCartIndexRouteImport
//       parentRoute: typeof rootRouteImport
//     }
//     '/OrderHistory/': {
//       id: '/OrderHistory/'
//       path: '/OrderHistory'
//       fullPath: '/OrderHistory'
//       preLoaderRoute: typeof OrderHistoryIndexRouteImport
//       parentRoute: typeof rootRouteImport
//     }
//     '/OrderConfirmationPage/': {
//       id: '/OrderConfirmationPage/'
//       path: '/OrderConfirmationPage'
//       fullPath: '/OrderConfirmationPage'
//       preLoaderRoute: typeof OrderConfirmationPageIndexRouteImport
//       parentRoute: typeof rootRouteImport
//     }
//     '/product/search': {
//       id: '/product/search'
//       path: '/product/search'
//       fullPath: '/product/search'
//       preLoaderRoute: typeof ProductSearchRouteImport
//       parentRoute: typeof rootRouteImport
//     }
//     '/product/productNotFound': {
//       id: '/product/productNotFound'
//       path: '/product/productNotFound'
//       fullPath: '/product/productNotFound'
//       preLoaderRoute: typeof ProductProductNotFoundRouteImport
//       parentRoute: typeof rootRouteImport
//     }
//     '/product/listingPage': {
//       id: '/product/listingPage'
//       path: '/product/listingPage'
//       fullPath: '/product/listingPage'
//       preLoaderRoute: typeof ProductListingPageRouteImport
//       parentRoute: typeof rootRouteImport
//     }
//     '/product/$productId': {
//       id: '/product/$productId'
//       path: '/product/$productId'
//       fullPath: '/product/$productId'
//       preLoaderRoute: typeof ProductProductIdRouteImport
//       parentRoute: typeof rootRouteImport
//     }
//     '/CheckOutPage/$tid': {
//       id: '/CheckOutPage/$tid'
//       path: '/CheckOutPage/$tid'
//       fullPath: '/CheckOutPage/$tid'
//       preLoaderRoute: typeof CheckOutPageTidRouteImport
//       parentRoute: typeof rootRouteImport
//     }
//     '/product/category/$category': {
//       id: '/product/category/$category'
//       path: '/product/category/$category'
//       fullPath: '/product/category/$category'
//       preLoaderRoute: typeof ProductCategoryCategoryRouteImport
//       parentRoute: typeof rootRouteImport
//     }
//   }
  }

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CheckOutPageTidRoute: CheckOutPageTidRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  ProductListingPageRoute: ProductListingPageRoute,
  ProductProductNotFoundRoute: ProductProductNotFoundRoute,
  ProductSearchRoute: ProductSearchRoute,
  OrderConfirmationPageIndexRoute: OrderConfirmationPageIndexRoute,
  OrderHistoryIndexRoute: OrderHistoryIndexRoute,
  ShoppingCartIndexRoute: ShoppingCartIndexRoute,
  ErrorIndexRoute: ErrorIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  OrderDetailsIndexRoute: OrderDetailsIndexRoute,
  ProductCategoryCategoryRoute: ProductCategoryCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
